---
- name: Create /home/{{ ssh_username }}/.config/pip directory 
  file: 
    path:   "/home/{{ ssh_username }}/.config/pip"
    state:  directory
    mode:   0755
    owner:  "{{ ssh_username }}"
    group:  "{{ ssh_username }}"
  when: inventory_hostname in groups['run_ssh_agent']

- name: Add proxied Python configuration to ~/.config/pip/pip.conf
  template:
    src: "proxied-pip-config.j2"
    dest: "/home/{{ ssh_username }}/.config/pip/pip.conf"
    owner: "{{ ssh_username }}"
    group: "{{ ssh_username }}"
    mode: 0644
  when: inventory_hostname in groups['run_ssh_agent']

- name: Create /home/{{ ssh_username }}/.m2 
  file: 
    path:   "/home/{{ ssh_username }}/.m2"
    state:  directory
    mode:   0755
    owner:  "{{ ssh_username }}"
    group:  "{{ ssh_username }}"
  when: inventory_hostname in groups['run_ssh_agent']

- name: Add proxied Maven Central configuration to ~/.m2/settings.xml
  template:
    src: "proxied-maven-settings-xml.j2"
    dest: "/home/{{ ssh_username }}/.m2/settings.xml"
    owner: "{{ ssh_username }}"
    group: "{{ ssh_username }}"
    mode: 0644
  when: inventory_hostname in groups['run_ssh_agent']
