---
- name: Configure Fedora to my liking.
  hosts: desktop
  become: true
  gather_facts: true
  roles:
    # https://galaxy.ansible.com/robertdebock/rpmfusion
    - robertdebock.rpmfusion
    - fedora-setup
