---
- name: Adding customisations to the {{ remote_home }}/.vimrc file
  template:
    src: "vimrc.j2"
    dest: "{{ remote_home }}/.vimrc"
    owner: "{{ remote_username }}"
    #group: "{{ remote_username }}"
    mode: 0644
