---
- name: Delete {{ remote_home }}/.ssh directory and content.
  file:
    state: absent
    path: "{{ remote_home }}/.ssh/"
  when: delete_ssh | default(false) # set in defaults/main.yml

- name: Create {{ remote_home }}/.ssh directory 
  file: 
    path:   "{{ remote_home }}/.ssh"
    state:  directory
    mode:   0700
    owner:  "{{ remote_username }}"
    #group:  "{{ remote_username }}"

# https://docs.ansible.com/ansible/latest/modules/authorized_key_module.html#examples
- name: Set a ssh authorized key from a file.
  authorized_key:
    user: "{{ remote_username }}"
    state: present
    #key: "{{ lookup('file', lookup('env', 'ANSIBLE_ROLES_PATH') + '/copy-ssh-keys/files/{{ ssh_centos6_public_key }}') }}"
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/{{ item }}') }}"
  with_items: "{{ ssh_auth_keys }}"

# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/copy_module.html
- name: Copy public ssh keys to ssh jumpboxes.
  copy:
    src: '{{ remote_home }}/.ssh/{{ item.public }}'
    dest: '{{ remote_home }}/.ssh/{{ item.public }}'
    owner: '{{ remote_username }}'
    #group: '{{ remote_username }}'
    mode: '0640'
  with_items: "{{ ssh_copy_keys }}"
  when: inventory_hostname in groups['run_ssh_agent']

- name: Copy private ssh keys to ssh jumpboxes.
  copy:
    src: '{{ remote_home }}/.ssh/{{ item.private }}'
    dest: '{{ remote_home }}/.ssh/{{ item.private }}'
    owner: '{{ remote_username }}'
    #group: '{{ remote_username }}'
    mode: '0600'
  with_items: "{{ ssh_copy_keys }}"
  when: inventory_hostname in groups['run_ssh_agent']

- name: Copy ssh config to ssh jumpboxes.
  template:
    src: 'ssh-config.j2'
    dest: '{{ remote_home }}/.ssh/config'
    owner: '{{ remote_username }}'
    #group: '{{ remote_username }}'
    mode: '0600'
  when: inventory_hostname in groups['run_ssh_agent']

# ssh-agent handled in setup-bash.yml
