all:
  hosts:
    desktop:
    pi:
    laptop-dell:
    laptop-dell-lan:
    laptop-toshiba:
    laptop-toshiba-lan:
  # https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#defining-variables-in-inventory
  vars:
    ansible_user: dallas
    ansible_connection: ssh
  children:
    pcs:
      desktop:
    laptops:
      laptop-dell:
      laptop-dell-lan:
      laptop-toshiba:
      laptop-toshiba-lan:
    pies:
      pi:
