all:
  hosts:
    desktop:
    pi:
    laptop-dell:
    laptop-dell-lan:
    laptop-toshiba:
    laptop-toshiba-lan:
  # https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#defining-variables-in-inventory
  vars:
    ansible_user: dallas
    ansible_connection: ssh
  children:
    my-desktop:
      hosts:
        desktop:
    my-dell-laptop:
      hosts:
        laptop-dell:
        laptop-dell-lan:
    my-toshiba-laptop:
      hosts:
        laptop-toshiba:
        laptop-toshiba-lan:
    my-pi:
      hosts:
        pi:
