- name: Import Visual Studio Code key
  rpm_key:
    state: present
    key: https://packages.microsoft.com/keys/microsoft.asc
  when: using_vs_code

- name: Add Visual Studio Code repository
  yum_repository:
    name: vscode
    description: Visual Studio Code YUM repo
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    gpgcheck: yes
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
  when: using_vs_code

- name: Import Visual Studio Codium key
  rpm_key:
    state: present
    key: https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg
  when: not using_vs_code

- name: Add Visual Studio Code repository
  yum_repository:
    name: vscodium
    description: Visual Studio Codium YUM repo
    baseurl: https://paulcarroty.gitlab.io/vscodium-deb-rpm-repo/rpms/
    gpgcheck: yes
    gpgkey: https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg
  when: not using_vs_code

# https://fedoraproject.org/wiki/Workstation/Third_Party_Software_Repositories#Managing_third_party_repositories_using_DNF
- name: Install Fedora Work Stations
  package:
    name: fedora-workstation-repositories
    state: present

# https://docs.fedoraproject.org/en-US/quick-docs/installing-chromium-or-google-chrome-browsers/
- name: Enable Google Chrome in fedora-workstation-repositories
  command: dnf config-manager --set-enabled google-chrome

- name: Install applications.
  # Don't use a loop its slow.
  package:
      name:
      - flatpak
      - ansible
      - tigervnc
      - keepassxc
      - bleachbit
      # Dev
      - jq
      - vim
      - gvim
      #- code
      - codium
      # Multimedia
      - vlc
      - strawberry
      # Archivers
      - p7zip
      - p7zip-plugins
      - unrar
      # Gaming
      - lutris
      - steam
      - playonlinux
      # Internet stuff
      - qbittorrent
      - quassel
      - thunderbird
      - weechat
      - firefox
      - google-chrome-stable
      # Disable mouse accel
      - xset
      - xinput
      # Pretty print sys info
      - neofetch
      - inxi
      # GUI menu editor
      - menulibre
      # Screenshots
      - shutter
      # Terminal file manager
      - mc
      # PDF reader
      - okular
      # Simple scanning
      - simple-scan
      # Mail
      - mailx
      - postfix
      # Sys monitoring
      - htop
      - iotop
      - lm_sensors
      - xsensors
      - logwatch
      # Benchmarking & stress tests
      - phoronix-test-suite
      - stress-ng
      - corectrl
      # SELinux
      - setroubleshoot
      - setroubleshoot-plugins
      # Display management
      - autorandr
      # MS Paint rip off
      - pinta
      # Disk tools
      - nvme-cli
      - smartmontools
      # Display keyboard strokes on screen
      - screenkey
      state: present
      update_cache: yes

- name: Install group packages.
  dnf:
    name:
    - "@Development tools"
    - "@Multimedia"
    - "@Sound-and-video"
    - "@i3-desktop-environment"
    - "@virtualization"
    state: present
    allowerasing: true # Needed to remove the free codecs which are automatically installed.

- name: Add Flathub
  command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

- name: Enable Flathub
  command: flatpak remote-modify --enable flathub

- name: Install AMD tools.
  package:
      name: "{{ item }}"
      state: present
  loop:
    - radeontop
  when: using_amd_gpu

- name: Upgrade all packages
  dnf:
    name: "*"
    state: latest
