---
- name: Adding customisations to the /home/{{ username }}/.bashrc file
  template:
    src: "bashrc-user.j2"
    dest: "/home/{{ username }}/.bashrc"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644

- name: Adding customisations to the /root/.bashrc file
  template:
    src: "bashrc-root.j2"
    dest: "/root/.bashrc"
    owner: root
    group: root
    mode: 0644

