# Change Gnome settings
- name: Update Gnome settings - Disable PackageKit downloads
  command: gsettings set org.gnome.software download-updates false

- name: Update Gnome settings - Set mouse speed to 0
  command: gsettings set org.gnome.desktop.peripherals.mouse speed 0.0

- name: Update Gnome settings - Remove mouse acceleration
  command: gsettings set org.gnome.desktop.peripherals.mouse accel-profile 'flat'

- name: Install Gnome stuff
  package:
    name:
    - gnome-extensions-app
    - gnome-shell-extension-appindicator
    - gnome-shell-extension-apps-menu
    - gnome-shell-extension-openweather
    - gnome-shell-extension-workspace-indicator
    #- gnome-shell-extension-sound-output-device-chooser
    - gnome-shell-extension-apps-menu
    - gnome-shell-extension-window-list
    - gnome-shell-extension-launch-new-instance
    - gnome-shell-extension-places-menu
    - gnome-shell-extension-drive-menu
    - gnome-shell-extension-user-theme
    - gnome-shell-extension-topicons-plus
    - gnome-shell-extension-gamemode
    - gnome-shell-extension-freon
    - gnome-shell-extension-drive-menu
    - gnome-tweaks
    - gnome-commander
    - gnome-pomodoro
    # GUI keyring manager
    - seahorse
    state: present
  # Ignore missing packages.
  ignore_errors: true

# Remove unwanted Gnome software - https://eklitzke.org/lobotomizing-gnome
# - name: Remove unwanted Gnome packages # Task description
#   dnf: # Specific package manager to use
#     name: # Package names
#       - cheese # Gnome web camera integration
#       - evolution # Gnome mail, contacts, and calendar.
#       - evolution-ews
#       - evolution-help
#       - gfbgraph # GLib/GObject wrapper for the Facebook API - https://wiki.gnome.org/Projects/GFBGraph
#       - gnome-boxes # VM
#       - gnome-contacts
#       - gnome-documents
#       - gnome-maps
#       - gnome-weather
#       - rhythmbox # Gnome music player
#       - totem # Gnome video player - https://github.com/GNOME/totem
#     state: absent # Uninstall packages

# Double-check that we still have the basics - https://eklitzke.org/lobotomizing-gnome
# - name: Ensure core Gnome packages are still installed
#   dnf:
#     name:
#       - eog
#       - evince
#       - evolution-data-server
#       - flatpak
#       - gdm
#       - gnome-keyring
#       - gnome-menus
#       - gnome-screenshot
#       - gnome-shell
#       - gnome-terminal
#       - gnome-tweaks
#       - nautilus
#       - redhat-menus
#     state: present # Install packages
