---
  # https://docs.ansible.com/ansible/latest/modules/yum_module.html
  # https://docs.ansible.com/ansible/latest/modules/dnf_module.html
  # https://www.jeffgeerling.com/blog/2018/reboot-and-wait-reboot-complete-ansible-playbook
  - name: Upgrade all packages.
    dnf:
      name: '*'
      state: latest
      update_cache: yes
      # Need to exclude for now because of containerd dependency error. See docker-install.yml
      exclude: docker-ce
    register: upgrade_result

  # https://docs.ansible.com/ansible/latest/modules/reboot_module.html
  - name: Reboot after upgrade.
    reboot:
    when: upgrade_result is changed
